version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "diogosouzas"
    assignees:
      - "diogosouzas"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "androidx.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.google.android.material"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "diogosouzas"
    assignees:
      - "diogosouzas"
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
